httpPort: 13000 # HTTP 服务的监听端口
MetricPort: 5859 # 应用的监控指标端口
appName: game    # 应用名称
log:
  level: DEBUG   # 日志级别
db:
  mongo:
    url: mongodb://127.0.0.1:27017 # MongoDB 数据库的连接地址
    userName: root                # MongoDB 数据库的用户名
    password: root123456          # MongoDB 数据库的密码
    minPoolSize: 10               # MongoDB 连接池的最小连接数
    maxPoolSize: 100              # MongoDB 连接池的最大连接数
    db: msqp                      # MongoDB 数据库的名称
  redis:
    addr: 127.0.0.1:6379          # Redis 数据库的连接地址
    poolSize: 10                  # Redis 连接池的大小
    minIdleConns: 1               # Redis 连接池的最小空闲连接数
    password:                     # Redis 数据库的密码（如果有的话）
jwt:
  secret: 123456 # JWT 的密钥
  exp: 7         # JWT 的过期时间（单位：天）

